### ISSUE TITLE
JPA 3장 영속성 관리

### ISSUE THREAD

**Issue by WonSteps** [YoonKeumJae/Spring_and_JPA_Study#20]

**Comment by GomDue** [comment]
Proxy의 정의가 무엇인가요??

**Comment by GomDue** [comment]
준영속은 어디에 사용되나요??

**Comment by GomDue** [comment]
JPQL과 JDBC의 차이점이 무엇인가요??

**Comment by WonSteps** [comment]
> Proxy의 정의가 무엇인가요??

프록시(Proxy)를 번역하면 대리자, 대변인의 의미를 갖고 있습니다. 그리고 대리자, 대변인은 누군가를 대신해서 그 역할을 수행하는 존재입니다. 즉, 프로그램에서 프록시에게 어떤 일을 대신 시키는 것입니다.

어떤 객체를 사용하고자 할때, 객체를 직접적으로 참조하는 것이 아닌 해당 객체를 대항하는 객체를 통해 대상 객체에 접근하는 방식을 사용하면 객체의 초기화 지연 및 기능 추가(로깅, 시간 측정, 캐싱), 흐름제어 등으로 다양하게 활용할 수 있다는 장점이 있습니다.

단점으로는 프록시 클래스를 구현해야 하며, 호출로 인한 오버헤드가 커질 수 있습니다.

**Comment by WonSteps** [comment]
> 준영속은 어디에 사용되나요??

비영속 상태와 같은 점은 둘다 변경 감지등 영속성 컨텍스트에 속하지 않습니다. 다른 점은 준영속 상태는 영속 상태가 한번되었던 상태이므로 식별자가 반드시 존재합니다.

일반적으로 이렇게 영속상태가 되었다가 바로 준영속 상태가 되는 일은 드물다고 생각합니다. 그래서 일부로 준영속을 만드는 경우보다는 다음과 같은 시나리오를 생각해볼 수 있습니다.

만약 엔티티를 조회했는데 트랜잭션이 끝나버리고 영속성 컨택스트도 사라지는 경우, 그때 조회한 엔티티는 준영속 상태가 됩니다. 이런 경우에 준영속 상태의 엔티티 객체가 생긴다고 볼 수 있을 것 같습니다.

**Comment by WonSteps** [comment]
> JPQL과 JDBC의 차이점

JPA는 다음과 같은 다양한 쿼리 방법을 지원합니다. : JPQL, JPA Criteria, QueryDSL, 네이티브 SQL
JPQL은 JPA에서 제공하는 문법으로 엔티티 객체를 대상으로 쿼리를 질의합니다.

이에 반해 SQL은 데이터베이스 테이블을 대상으로 쿼리를 질의합니다.

JDBC의 경우, JPA와는 상관없는 인터페이스로, DB 드라이버를 사용해서 자바 응용 프로그램이 데이터베이스와 연결, 통신을 할 수 있게 연결해주는 인터페이스입니다.
