### ISSUE TITLE
2.4 환경 프로퍼티 파일 설정하기

### ISSUE THREAD

**Issue by Jaewon-pro** [YoonKeumJae/Spring_and_JPA_Study#6]

**Comment by YoonKeumJae** [comment]
SqEL에 대해 자세히 설명해주세요.

**Comment by YoonKeumJae** [comment]
POJO type에 대해 설명해주세요.

**Comment by Jaewon-pro** [comment]
> SqEL에 대해 자세히 설명해주세요.

Spring Expression Language(SpEL)는 런타임에 객체 그래프를 쿼리하고 조작하는 것을 지원하는 표현 언어입니다. 언어 구문은 추가 기능, 특히 메서드 호출 및 기본 문자열 템플릿 기능을 제공합니다.

parser를 이용하면 연산자 호출, 메서드 호출을 문자열을 통해서 실행할 수 있습니다.

[참고](https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/expressions.html)

**Comment by Jaewon-pro** [comment]
> POJO type에 대해 설명해주세요.

POJO type은 Plain Old Java Objects로 순수한 자바 문법으로만 만들어진 클래스를 의미합나다.
만약 클래스가 어느 프레임워크에 종속적거나 다른 클래스를 implements 했거나 상속받은 클래스는 POJO 타입이라고 할 수 없습니다.

스프링에서는 다른 클래스를 implements하는 대신, '@' 어노테이션을 적극 활용해서 클래스간의 결합도를 줄이는 방법을 고안했습니다.

예를 들어, 최근 Deprecated된 WebSecurityConfigurerAdapter 추상 클래스를 보면, 추상 클래스의 configure 함수를 오버라이드해서 사용하기 보다는 '@Bean' 어노테이션을 활용하기 위해서 삭제되었다고 생각합니다.
